### ISSUE TITLE
updateRecord writes data not record to json

### ISSUE THREAD

**Issue by KevinAHM** [KetanIP/jsondbb#1]
line 102 in db.py
`filo.writeJson(data_temp, data)`
Should be
`filo.writeJson(data_temp, record)`

**Comment by ketanip** [comment]
Thanks you for pointing it out. I will take a look into code and fix it as soon as possible along with other issue you raised.

**Comment by ketanip** [comment]
Hope [this ](https://github.com/ketanip/dbjson/commit/6640eb1cd48960fa87738f0edd600ae5cc8f929a) commit fixes the above mentioned problems. Let me know if you ever find another bug. 

New contributions from your side will always be welcomed.
