### ISSUE TITLE
remote support?

### ISSUE THREAD

**Issue by ghost** [KetanIP/jsondbb#4]

**Comment by ketanip** [comment]
Using Nostr for storing JSON data and syncing it locally with dbjson sound like a great idea. But I think there are some topics that needs some attention,

1. Nostr allows only 2 kinds of entities ( 0: metadata and 1:text only posts) and for kind 1 it need to simple text as specified on the [project docs](https://nostr.com/the-protocol/events). So if we store JSON data as text, it will break the protocol for many and many clients will not be able to parse it properly.

2. If we change kind to say to 2 even in that case it will break many clients.

3. For local storage of data which is in sync with a cloud based database or decentralized database (in this case) I would suggest you to use something like local storage in browsers and on proper servers / desktop apps / mobiles apps a good old SQLite database they are really easy to use. Just used a normalized schema model of key-value pairs if you want to follow NoSQL model in SQLite.

I think this proposal could be more appropriate to [Nostr's New Ideas Proposals's repository](https://github.com/nostr-protocol/nips) as they could incorporate this into the protocol itself.

But if you want to go ahead with this you can just store JSON as text and kind as 1 to reduce the amount of mismatch of expectations between the clients and servers.  

Let me know what you think about this.
